pipeline {
    agent any

    stages {
        stage('Pull code') {
            steps {
               checkout scm
            }
        }
        stage('Download dependency') {
            steps {
                 dir('Backend') {
                    sh 'npm install'
                }
            }
        }
        stage('Run unit test') {
            steps {
                dir('Backend') {
                   sh 'npm run test'
                }
                
            }
        }
        stage('Run Integration test') {
            steps {
                echo 'run component test'
            }
        }

        stage('Deployment') {
            steps {

               script {
                def remote = [:]
                remote.name = 'T09'
                remote.host = '159.223.45.216'
                remote.user = 'root'
                remote.password = 'xitgmLwmp12q'
                remote.allowAnyHosts = true
                sshCommand remote: remote, command: "git clone https://github.com/fluke1352/DEVELOPMENT-TOOLS-GET-A-PLUS.git"
                sshCommand remote: remote, command: "docker-compose -f DEVELOPMENT-TOOLS-GET-A-PLUS/docker-compose-deploy-back.yml up -d"
                sshCommand remote: remote, command: "rm -r DEVELOPMENT-TOOLS-GET-A-PLUS"
                    
                }
                
            }
        }
        stage('Versioning') {
            steps {
               withCredentials([gitUsernamePassword(credentialsId: 'devtool9', gitToolName: 'Default')]) {
                    sh 'git tag ' + 'v1.0.' + BUILD_NUMBER
                    sh 'git tag'
                    sh 'git push origin ' + 'v1.0.' + BUILD_NUMBER
               }
            }
        }
    }
}
