pipeline {
    agent any

    stages {
        stage('Pull code') {
            steps {
               checkout scm
            }
        }
        stage('Download dependency') {
            steps {
                 dir('Backend') {
                    sh 'npm install'
                }
            }
        }
        stage('Run unit test') {
            steps {
                dir('Backend') {
                   sh 'npm run test'
                }
                
            }
        }
        stage('Run Integration test') {
            steps {
                echo 'run component test'
            }
        }
//         stage('build') {
//             steps {
//             dir('Backend') {
//                 sh 'docker image build devtool09/team-9-backend:1.0.2'
//                  withCredentials([string(credentialsId: 'T09_PASSWORD', variable: 'T09_PASSWORD')]) {
//                      sh 'docker login'
//                      sh $T09_PASSWORD
//                      sh $T09_PASSWORD
//                     }
//                     sh 'docker push devtool09/team-9-backend:1.0.2'
//                 }
//             }
//         }
        stage('Deployment') {
            steps {
                  sshagent([string(credentialsId: 'T09_BACKEND_USERNAME', variable: 'T09_USERNAME')]){
                        sh 'ssh $T09_USERNAME'
                   }
                  sshagent([string(credentialsId: 'T09_BACKEND_PASSWORD', variable: 'T09_PASSWORD')]){
                      sh '$T09_PASSWORD'
                  }
                sh 'git clone https://github.com/fluke1352/DEVELOPMENT-TOOLS-GET-A-PLUS.git'
                dir('DEVELOPMENT-TOOLS-GET-A-PLUS'){
                    sh 'docker-compose -f docker-compose-deploy-back.yml up -d'
                }
                sh 'rm -r DEVELOPMENT-TOOLS-GET-A-PLUS.git'             
                
            }
        }
    }
}
