pipeline {
    agent any
stages {
   stage('Pull code') {
       steps {
           checkout scm
       }
   }
   stage('Download dependency') {
       steps {
           dir('Frontend/wannaplay-webapp') {
               sh 'npm install'
           }
       }
   }
   stage('Run unit test') {
        steps {
              dir('Frontend/wannaplay-webapp') {
                   sh 'npm run test'
              }
        }
   }
   stage('Run Integration test') {
       steps {
           echo 'run component test'
       }
   }
   stage('Build') {
       steps {
           
          dir('Frontend/wannaplay-webapp') {
               sh 'npm run-script build'
           }
       }
   }
    
   stage('Deployment') {
        steps{
                withCredentials([string(credentialsId: 'T09_FRONTEND_PASS', variable: 'T09Pass')]) {
                    echo '${T09Pass}'
                }
                script {
                def remote = [:]
                remote.name = 'T09'
                remote.host = '159.65.12.177'
                remote.user = 'root'
                remote.password = 'jim'
                remote.allowAnyHosts = true
                sshCommand remote: remote, command: "git clone https://github.com/fluke1352/DEVELOPMENT-TOOLS-GET-A-PLUS.git"
                sshCommand remote: remote, command: "cd DEVELOPMENT-TOOLS-GET-A-PLUS"
                sshCommand remote: remote, command: "docker-compose -f docker-compose-deploy-front.yml up -d"
                sshCommand remote: remote, command: "cd .."
                sshCommand remote: remote, command: "rm -r DEVELOPMENT-TOOLS-GET-A-PLUS"
                    
                }
            
            
        }       
      }
          
   }
    
 }

